url: https://imxixi.cn
baseurl: /about/

# Site settings
title: 夕夕
email: mx.xi@foxmail.cn
description: "本人虽然有着两年的研发经验以及近三年的项目运维工作经验，可以让我在与开发沟通时能保持在同一个频率，还会参与项目的需求及测试相关工作，了解整个项目各个节点所运行的流程，但在在业余生活中也会研究其它领域的业务并且学习行业相关的知识。"


# Team names, titles and social links
people:
- name: 嘻嘻
  pic: 1
  position: 生命中不可或缺的伙伴
  social:
    - title: yarn
      url: #
    - title: yarn
      url: #
    - title: yarn
      url: #

- name: 夕夕
  pic: 2
  position: 立志于成为更好的自己
  social:
    - title: link
      url: https://imxixi.cn/ #
    - title: github
      url: https://github.com/mxxixi/ #
    - title: book
      url: https://www.xiaohongshu.com/user/profile/5cf77a250000000025019e80 #

- name: 夜明
  pic: 3
  position: 将伴随我一生的人
  social:
    - title: link
      url: https://lixiaoxu.cn/ #
    - title: github
      url: https://github.com/lixx-code #
    - title: weibo
      url: https://weibo.com/LxxDawn #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: book
    url: https://www.xiaohongshu.com/user/profile/5cf77a250000000025019e80 #http://twitter.com/jekyllrb
  - title: link
    url: https://imxixi.cn/ #
  - title: tv
    url: https://space.bilibili.com/457038975/dynamic #http://stackoverflow.com/questions/tagged/jekyll
  - title: weibo 
    url: https://m.weibo.cn/profile/6867557735 #http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/mxxixi/ #http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
